public class Main {
    public static void main(String[] args) {
        MusicCollection[] categories = new  MusicCollection[2];
        categories[0] = new MusicCollection();
        categories[1] = new MusicCollection();
        MusicCollection pop = new MusicCollection();
        MusicCollection jazz = new MusicCollection();
        MusicCollection rock = new MusicCollection();
        MusicCollection country = new MusicCollection();
        Music b1 = new Music("C:\\Users\\jazz.mp3","Hooman", 1998);
        Music c1 = new Music("C:\\Users\\rock.mp3","Mohsen", 1995);
        Music d1 = new Music("C:\\Users\\country.mp3","Ramin", 2000);
        Music e1 = new Music("C:\\Users\\category1\\music1.mp3","Taghi", 2005);
        Music f1 = new Music("C:\\Users\\category1\\music2.mp3","Naghi", 2010);
        jazz.addFile(b1);
        rock.addFile(c1);
        country.addFile(d1);
        categories[0].addFile(e1);
        categories[1].addFile(f1);
        Music a1 = new Music("C:\\Users\\1.mp3","Armin", 2020);
        Music a2 = new Music("C:\\Users\\2.mp3","Hassan", 2020);
        Music a3 = new Music("C:\\Users\\3.mp3","Ali", 2020);
        Music a4 = new Music("C:\\Users\\4.mp3","Reza", 2019);
        pop.addFile(a1);
        pop.addFile(a2);
        pop.addFile(a3);
        pop.addFile(a4);

        System.out.println(pop.getNumberOfFiles());
        System.out.println();
        pop.listFile(5);
        System.out.println();
        pop.listFile(3);
        System.out.println();
        pop.listAllFiles();
        pop.removeFile(2);
        System.out.println();
        pop.listFile(3);
        System.out.println();
        pop.listAllFiles();
        System.out.println();
        pop.startPlaying(2);
        System.out.println();
        pop.stopPlaying();
        System.out.println();
        pop.stopPlaying();
        System.out.println();
        pop.addFavorite(2);
        System.out.println();
        pop.addFavorite(2);
        System.out.println();
        pop.removeFavorite(2);
        System.out.println();
        pop.removeFavorite(2);
        System.out.println();
        pop.listAllFilesFavorite();
        System.out.println();
        pop.addFavorite(2);
        System.out.println();
        pop.addFavorite(3);
        System.out.println();
        pop.listAllFilesFavorite();
        System.out.println();
        pop.search(".mp3");
        System.out.println();
        pop.search("ali");
        System.out.println();
        pop.search("2020");
    }
}
